In [3]:
import numpy as np
A = np.random.randint(0, 10, [2,3])
B = np.ones((1, 3))

In [4]:
A

array([[5, 8, 0],
       [3, 5, 9]])

In [5]:
A + B 

array([[ 6.,  9.,  1.],
       [ 4.,  6., 10.]])

In [6]:
tableau = np.array ([1, 2, 3])
tableau.shape 

(3,)

In [7]:
tableau= tableau.reshape(tableau.shape[0], 1)

In [8]:
tableau.shape

(3, 1)

In [9]:
A.sum (axis = 0)

array([ 8, 13,  9])

In [10]:
A.sum (axis = 1)

array([13, 17])

In [11]:
A.cumsum ()

array([ 5, 13, 13, 16, 21, 30])

In [12]:
A.min (axis=0)   # position du minimum

array([3, 5, 0])

In [13]:
A.argmin (axis=0)

array([1, 1, 0], dtype=int64)

In [14]:
A.sort ()

In [15]:
np.exp(A)

array([[1.00000000e+00, 1.48413159e+02, 2.98095799e+03],
       [2.00855369e+01, 1.48413159e+02, 8.10308393e+03]])

In [16]:
A.mean()

5.0

In [17]:
A.var ()

9.0

In [18]:
A.std()   #ecart-type

3.0

In [19]:
B =np.corrcoef(A)
B.shape

(2, 2)

In [20]:
B[0,1]

0.9449111825230679

In [21]:
np.corrcoef(A)[0,1]

0.9449111825230679

In [22]:
C = np.random.randint(0,10, [5,5])

In [23]:
C

array([[5, 2, 8, 0, 4],
       [9, 8, 8, 7, 6],
       [9, 3, 6, 5, 8],
       [1, 9, 2, 9, 5],
       [4, 6, 7, 5, 5]])

In [24]:
values, counts =np.unique(C, return_counts=True)    # classe les elements et donne le nombre de fois que le nombre se repete

In [25]:
print (values, counts) 

[0 1 2 3 4 5 6 7 8 9] [1 1 2 1 2 5 3 2 4 4]


In [26]:
counts.argsort()  # done l'index de chaque elment pour les calsser en ordre

array([0, 1, 3, 2, 4, 7, 6, 8, 9, 5], dtype=int64)

In [27]:
values [counts.argsort()]     # classe le nombre qui aparait du moins au plus 

array([0, 1, 3, 2, 4, 7, 6, 8, 9, 5])

In [28]:
(counts.sort())

In [29]:
for i,j in zip(values [counts.argsort()], counts[counts.argsort()]) : 
    print (f"la valeur {i} apparait {j} fois")

la valeur 0 apparait 1 fois
la valeur 1 apparait 1 fois
la valeur 2 apparait 1 fois
la valeur 3 apparait 2 fois
la valeur 4 apparait 2 fois
la valeur 5 apparait 2 fois
la valeur 6 apparait 3 fois
la valeur 7 apparait 4 fois
la valeur 8 apparait 4 fois
la valeur 9 apparait 5 fois


Pour des elements de ton tableau qui sont nan et que tu aimerait calculer la variance ou la moyenn 
ou alors l'ecart type tu peux utiliser np.nanmean(), np.nanstd(), np.nanvar(), np.isnan() donne le ndarray sous forme
boolean avec les TRue ou il ya nanet pour les mettre a 0 on fait l'indexing A: matrix , A[np.isnan(A)] = 0

In [30]:
A = np.ones((2,3))
A

array([[1., 1., 1.],
       [1., 1., 1.]])

In [31]:
B = np.ones ((3,2))
B

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [32]:
A.T

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [33]:
A.dot(B)   # produit matricielle

array([[3., 3.],
       [3., 3.]])

In [34]:
A= np.random.randint(0,10, [3,3])
np.linalg.det(A)

-138.00000000000006

In [35]:
np.linalg.inv(A)

array([[ 0.18115942, -0.08695652, -0.04347826],
       [ 0.05072464, -0.30434783,  0.34782609],
       [-0.06521739,  0.39130435, -0.30434783]])

In [36]:
np.linalg.eig(A)

EigResult(eigenvalues=array([17.07005854,  5.42118843, -1.49124697]), eigenvectors=array([[ 0.60774953, -0.99301965, -0.0329139 ],
       [ 0.59211119, -0.02037983, -0.68587773],
       [ 0.52919263,  0.11617504,  0.72697209]]))

In [37]:
np.random.seed(0)
A = np.random.randint(0, 100, [10 ,5])
A

array([[44, 47, 64, 67, 67],
       [ 9, 83, 21, 36, 87],
       [70, 88, 88, 12, 58],
       [65, 39, 87, 46, 88],
       [81, 37, 25, 77, 72],
       [ 9, 20, 80, 69, 79],
       [47, 64, 82, 99, 88],
       [49, 29, 19, 19, 14],
       [39, 32, 65,  9, 57],
       [32, 31, 74, 23, 35]])

In [38]:
B = A.mean(axis=0)
B

array([44.5, 47. , 60.5, 45.7, 64.5])

In [39]:
C = A.std (axis=0)
C

array([22.66384786, 22.28003591, 26.5678377 , 29.36341261, 23.2432786 ])

In [40]:
E = (A-B)/C
E

array([[-0.02206157,  0.        ,  0.13173823,  0.72539252,  0.10755798],
       [-1.56637126,  1.61579632, -1.48676006, -0.33034307,  0.96802178],
       [ 1.12513992,  1.84021247,  1.03508612, -1.14768676, -0.27965074],
       [ 0.90452425, -0.35906585,  0.99744662,  0.0102168 ,  1.01104497],
       [ 1.6104944 , -0.44883231, -1.33620208,  1.0659524 ,  0.32267393],
       [-1.56637126, -1.21184724,  0.73397016,  0.7935045 ,  0.62383626],
       [ 0.11030784,  0.76301493,  0.80924915,  1.81518411,  1.01104497],
       [ 0.1985541 , -0.80789816, -1.56203905, -0.90929485, -2.17267111],
       [-0.24267724, -0.67324847,  0.16937773, -1.24985473, -0.32267393],
       [-0.55153918, -0.7181317 ,  0.50813319, -0.77307091, -1.26918412]])

In [41]:
print(A[:,0], B, C)
D =np.zeros((10,5))
D[0,0] = (A[0,0]-B[0])/C[0]
D[1,0] = (A[1,0]-B[0])/C[0]
D[2,0] = (A[2,0]-B[0])/C[0]

[44  9 70 65 81  9 47 49 39 32] [44.5 47.  60.5 45.7 64.5] [22.66384786 22.28003591 26.5678377  29.36341261 23.2432786 ]


In [42]:
D =np.zeros((10,5))
def dataset ():
    for j in range(5):
        for i in range(10):
            D[i,j] = (A[i,j]-B[j])/C[j]
    return D
dataset ()

array([[-0.02206157,  0.        ,  0.13173823,  0.72539252,  0.10755798],
       [-1.56637126,  1.61579632, -1.48676006, -0.33034307,  0.96802178],
       [ 1.12513992,  1.84021247,  1.03508612, -1.14768676, -0.27965074],
       [ 0.90452425, -0.35906585,  0.99744662,  0.0102168 ,  1.01104497],
       [ 1.6104944 , -0.44883231, -1.33620208,  1.0659524 ,  0.32267393],
       [-1.56637126, -1.21184724,  0.73397016,  0.7935045 ,  0.62383626],
       [ 0.11030784,  0.76301493,  0.80924915,  1.81518411,  1.01104497],
       [ 0.1985541 , -0.80789816, -1.56203905, -0.90929485, -2.17267111],
       [-0.24267724, -0.67324847,  0.16937773, -1.24985473, -0.32267393],
       [-0.55153918, -0.7181317 ,  0.50813319, -0.77307091, -1.26918412]])